name: Package Python

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        top_dir="$( realpath "$( find -mindepth 1 -maxdepth 2 -name "setup.py" | head -1 )"; )"
        top_dir="$( dirname "$top_dor"; )"
        echo "top_dir=$top_dir" 1>&2
        cd "$top_dir"
        python -m pip install --upgrade --force-reinstall setuptools pip wheel pytest coverage profiling pytest-cov
        python -m pip install -r requirements.txt
        sudo apt install remake -y
        remake --trace -k -B || true
        python setup.py egg_info || true
        python setup.py bdist_info || true
        python setup.py build_egg || true
        python setup.py bdist_egg || true
        python setup.py egg || true
        python setup.py build_whl || true
        python setup.py bdist_whl || true
        python setup.py wheel || true
        python setup.py egg-info || true
        python setup.py bdist-info || true
        python setup.py build-egg || true
        python setup.py bdist-egg || true
        python setup.py build || true
        python setup.py build-whl || true
        python setup.py bdist-whl || true
        python -m pip install -v -v -v dist/uncompyle6-3.7.5.dev0-py3.9.egg || \
        python setup.py install  || true
        whl="$( find "$top_dir" -name "*.whl" -mmin -5 | head -1 )"
        if [ -n "$whl" ]; then
          echo "whl=$whl" 1>&2
          python -m pip install "$whl" || true
        else
          python setup.py develop || true
        else
          true
        fi
        python -m pytest -vv --full-trace --color=yes  --cov=uncompule6 --cov-append
